### ISSUE TITLE
wrong profile parsing from ~/.aws/config

### ISSUE THREAD

**Issue by gdamjan** [marceloboeira/awsudo#16]
According to the docs [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html?shortFooter=true) (and the behavior of the aws-cli tool), the profiles, ie. the section names in the ~/.aws/config file should be prefixed with "`profile`", for example:

```
[profile user1]
region=us-east-1
output=text
```

while awsudo, expects it to be just `[user1]`.

**Comment by marceloboeira** [comment]
Thanks for reporting @gdamjan.

**Comment by marceloboeira** [comment]
Fixed here: 0ba707eb3fde6e94855a4b4bdae5929bbeaf5bfb
